config/routes.rb
ThecityAppSkills::Application.routes.draw do

  root :to => 'skills#index'

  ##################################################################
  ## Skills ##
  ##################################################################
  resources :skills, :only => [:index, :show] do
    member do
      get :email_new
    end
  end

  resource :skills, :only => [] do
    member do
      post :search
      post :send_email
    end
  end    

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :external_id, :name

  has_many :user_skills, :dependent => :destroy
  has_many :users, :through => :user_skills
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :external_id,
                  :active, 
                  :first_name, 
                  :nickname,
                  :last_name, 
                  :gender, 
                  :email,
                  :primary_phone,
                  :primary_phone_type,
                  :secondary_phone,
                  :secondary_phone_type,
                  :primary_campus,
                  :memberized_at,
                  :last_engaged_at,
                  :last_logged_in_at

  has_many :user_skills, :dependent => :destroy
  has_many :skills, :through => :user_skills  


  scoped_search :in => :skills, :on => [:name]

  def full_name
    fname = self.nickname.nil? ? self.first_name : self.nickname
    [fname, self.last_name].join(' ')
  end
  
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  attr_accessible :skill_id, :user_id

  belongs_to :skill, :counter_cache => :user_count  
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index
    @skills = Skill.order('name ASC')
  end


  def show
    @skill = Skill.includes(:users).find(params[:id])
    
    @users = @skill.users
  end

  
  def search
    @users = []
    if params[:query].present?
      @users = User.search_for(params[:query]).order('first_name ASC')
    end
  end


  def email_new
    # nothing to do here
  end

  def send_email
    if params[:user_id].present? and params[:message].present? and User.exists?(params[:user_id])
      user = User.find_by_id(params[:user_id])

      if user.nil?
        @errors = 'User not found'
      else
        UserMailer.you_have_mail(user, params[:message]).deliver
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper

  def display_phone_numbers(user)
    phones = []
    unless user.primary_phone.blank?
      ltr = user.primary_phone_type.first.downcase
      phones << "(#{ltr}) #{user.primary_phone}"
    end

    unless user.secondary_phone.blank?
      ltr = user.secondary_phone_type.first.downcase
      phones << "(#{ltr}) #{user.secondary_phone}"
    end

    phones.empty? ? 'N/A' : phones.join('<br>').html_safe
  end


  def display_time(t)
    return 'Unknown' if t.nil?
    t.class == DateTime ? t.to_s(:short_stamp) : t.to_s(:basic_date)
  end


  def display_options(user)
    skills = user.skills.collect { |s| s.name }.join('||')
    
    [ link_to_function('Skills', 'show_user_skills_list( $(this) )') + 
        hidden_field_tag("user_#{user.id}", skills, {:class => 'skills'} ),
      link_to('Email', email_new_skill_path) + 
        hidden_field_tag("user_email_#{user.id}", user.id, {:class => 'user_id'}) ].join(' | ').html_safe
  end

end

app/views/layouts/_search_bar.html.haml
.navbar
  .navbar-inner
    .container
      = link_to('Skills on The City', skills_path, {:class => 'brand'})
      = form_tag(search_skills_path, :class => "navbar-search search-query pull-right") do
        = search_field_tag(:query, nil, {:class => "search-query", :placeholder => "search skills", :type => "tex"})
        = submit_tag('Search', {:class => "btn"})

app/views/layouts/application.html.erb
!!! 5
%html
  %head
    %title City Skills

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield
    

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title City Skills

    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "bootstrap.min", :media => "all"
    = stylesheet_link_tag    "jquery.dataTables", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "jquery.dataTables.min"
    = csrf_meta_tags

  %body
    #container
      .inner_container{:style => 'margin: 0px auto 0px auto; width: 800px;'}
        = render :partial => '/layouts/search_bar'  
        = yield
    

app/views/skills/_users_table.html.haml
%table#users
  %thead
    %tr
      %th Name
      %th Contact
      %th Membership
      %th Last Engaged
      %th Last Login
      %th Options

  %tbody
    - @users.each do |user|
      %tr
        %td= user.full_name
        %td= display_phone_numbers(user)
        %td= display_time(user.memberized_at)
        %td= display_time(user.last_engaged_at)
        %td= display_time(user.last_logged_in_at)
        %td= display_options(user)

= javascript_tag('user_table_formatting()')

app/views/skills/email_new.html.haml
.email_form
  = form_tag(send_email_skills_path, {:class => 'form-horizontal'}) do
    .control-group
      %label{:class => 'control-label', :for => 'message'} Message
      .controls
        = text_area_tag(:message, nil, {:rows => 5, :style => 'width: 400px'})
        = hidden_field_tag(:user_id, params[:id])

    .control-group
      .controls
        = link_to_function('Cancel', 'javascript:history.back()', {:class => 'btn btn-link'})
        = submit_tag('Send', {:class => 'btn'})

app/views/skills/index.html.haml
%ul
  - if @skills.size == 0
    %li No Skills Found

  - else  
    - @skills.each do |skill|
      %li= link_to("#{skill.name} (#{skill.user_count})", skill_path(skill.id))

app/views/skills/search.html.haml
%h2 Search Results
%hr

= render :partial => 'users_table'

app/views/skills/send_email.html.haml
= link_to('Return to Skills', skills_path)
%br
%br
- if @errors
  Unable to send message.
- else
  Email successfully sent!

app/views/skills/show.html.haml
%h2= @skill.name
%hr

= render :partial => 'users_table'